### ISSUE TITLE
Allow Hooks to be sent for a specific user or all users.

### ISSUE THREAD

**Issue by bogdanpetrea** [PressLabs/django-rest-hooks#3]
At the moment you need to have a user field/property defined in the model you use the hook for.
Also you can use the "all users" behaviour, by specifying a '+' in the HOOK_EVENTS settings, which is bad and out of place. 
This needs to be defined in the Hook model.

**Comment by calind** [comment]
Agree with you. This was implemented by extending the `Hook` model with `global_hook` flag.
